name: PR Checks

on:
  pull_request:
    branches: [main]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.clang-format'
      - 'makefile'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: Bacondish2023/setup-googletest@v1

    - name: Run tests
      run: make test

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check formatting with dprint
      uses: dprint/check@v2.3

    - name: Check formatting with clang-format
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: 18
        check-path: .
