name: PR Checks Tests

on:
  pull_request:
    branches: [main]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.clang-format'
      - 'makefile'
      - '.github/workflows/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: Bacondish2023/setup-googletest@v1

    - name: Run tests
      run: make test
